pipelines:
  - name: basic_state
    steps:
      - name: one
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: "pipelines-api"
            JFROG_CLI_BUILD_NUMBER: "${run_id}"
          integrations:
            - name: art
          runtime:
            type: host
        execution:
          onExecute:
            - add_pipeline_variables run=$run_number
            - add_run_variables run="$run_number lol"
            - touch foo
            - add_run_files foo foo
            - add_pipeline_files foo foo
            - jfrog rt build-collect-env ${JFROG_CLI_BUILD_NAME} ${JFROG_CLI_BUILD_NUMBER}
            - jfrog rt build-publish ${JFROG_CLI_BUILD_NAME} ${JFROG_CLI_BUILD_NUMBER}
      - name: two
        type: Bash
        configuration:
          inputSteps:
            - name: one
          runtime:
            type: host
        execution:
          onExecute:
            - restore_run_files foo foo
            - printenv
