pipelines:
  - name: basic_state
    steps:
      - name: one
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - add_pipeline_variables run=$run_number
            - add_run_variables run="$run_number lol"
            - touch foo
            - add_run_files foo foo
            - add_pipeline_files foo foo
      - name: two
        type: Bash
        configuration:
          inputSteps:
            - name: one
          runtime:
            type: host
        execution:
          onExecute:
            - restore_run_files foo foo
            - printenv
