resources:
  - name: myRepo_d
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^monorepo*$
        exclude: ^master$
  - name: myRepo_5
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        exclude: ^master$
  - name: myRepo_6
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: (master|(release|milestone)\/[0-9]+-.*|(preRelease|bugfix|feature|hotfix|infra)\/.*)
        exclude: ^master$

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_d1
        execution:
          onExecute:
            - printenv
            - echo "hi"

