resources:
  - name: newVersion_conditional
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: new_demo_run
    steps:
      - name: step_AA
        type: Bash
        configuration:
          inputResources:
            - name: newVersion_conditional
              newVersionOnly: true
        execution:
          onExecute:
            - echo "Executing step_AA"
            - printenv

      - name: step_CC
        type: Bash
        execution:
          onExecute:
            - echo "Executing step_CC"
            - printenv
     
      - name: conditional_DD
        type: Bash
        configuration:
          inputSteps:
            - name: step_CC
              status:
                - success
            - name: step_AA
              status:
                - failure
                - skipped
                - cancelled
        execution:
          onExecute:
            - echo "Executing conditional_DD"
            - printenv
 
