resources:
  - name: myRepo_d
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub

pipelines:
  - name: demo_manual_1
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_d
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
