resources:
  - name: myRepo_2
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: demo_manual
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_2
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - echo "here"
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo "here"

            

