resources:
  - name: gitRepo_matrix
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub

pipelines:
  - name: maatrix_bash_pipeline
    steps:
      - name: testBash_matrix
        type: Matrix
        configuration:
          inputResources:
            - name: gitRepo_matrix
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
        execution:
          onExecute:
            - docker images        
            - df -h
            - printenv
            - echo "Executing testBash_aws step"
