resources:
  - name: myRepo_test
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
  - name: newRepo_test
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
  - name: script_1_test
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
      files:
        include: echo.sh
  - name: script_2_test
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
      files:
        include: node.sh
  - name: propertyBag_test
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: script_2_test
          outputResources:
            - name: propertyBag_test
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
            - printenv
  - name: demo_monorepo
    steps: 
      - name: demoBash_main
        type: Bash
        configuration:
          inputResources:
            - name: script_1_test
#             - name: propertyBag
        execution:
          onExecute:
            - echo "Executing demoBash_main"
            - sleep 60
      - name: demoBash_monorepo
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_test
              trigger: false
#             - name: propertyBag
          inputSteps:
            - name: demoBash_main
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
      - name: demoBash_monorepo_2
        type: Bash
        configuration:
          inputResources:
            - name: newRepo_test
#             - name: myRepo
          inputSteps:
            - name: demoBash_monorepo
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
            
            
#       - name: demoBash_monorepo_3_test
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: demoBash_monorepo_2
#         execution:
#           onExecute:
#             - echo "Executing demoBash_monorepo_2_test"
            
            
