resources:
  - name: script_1_2
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: demo_triggeredBy
    steps:
      - name: demoBash
        type: Bash
        configuration:
          inputResources:
            - name: script_1_2
        execution:
          onExecute:
            - echo "Executing demoBash"
            - printenv
            
