resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
  - name: newRepo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
      buildOn:
        commit: false
        pullRequestCreate: true
        pullRequestClose: true
        releaseCreate: true
        tagCreate: true
  - name: script_1
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
      files:
        include: echo.sh
  - name: script_2
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
      files:
        include: node.sh
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: script_2
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
  - name: demo_monorepo
    steps: 
      - name: demoBash_main
        type: Bash
        configuration:
          timeoutSeconds: 300
          inputResources:
            - name: script_1
#             - name: propertyBag
        execution:
          onExecute:
            - echo "Executing demoBash_main"
      - name: demoBash_monorepo
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
              trigger: false
#             - name: propertyBag
          inputSteps:
            - name: demoBash_main
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
      - name: demoBash_monorepo_2
        type: Bash
        configuration:
          inputResources:
            - name: newRepo
#             - name: myRepo
          inputSteps:
            - name: demoBash_monorepo
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
            - echo "here1"
            
#       - name: demoBash_monorepo_3_test
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: demoBash_monorepo_2
#         execution:
#           onExecute:#
#             - echo "Executing demoBash_monorepo_2_test"
            
           

