resources:
  - name: myRepo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      files:
        include: \bfolder2\/.+\b
      buildOn:
         commit:            true
         pullRequestCreate: true
         pullRequestClose:  true
         releaseCreate:     false
         tagCreate:         false
      
  - name: propertyBag
    type: PropertyBag
    configuration:
      info: ""

  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: deepika_art
      buildNumber: 1
      buildName: sampleStep

pipelines: 
  - name: demo_manual
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - write_output propertyBag "info=$run_number"
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: propertyBag
        execution:
          onExecute:
            - echo $res_propertyBag_info
