resources:
  - name: myRepo_d
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: .+
        exclude: ^master$

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo_d
        execution:
          onExecute:
            - printenv
