resources:
  - name: newRepo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
      buildOn:
         commit:            true
      
  - name: myVersion
    type: PropertyBag
    configuration:
      info: "version"

pipelines: 
  - name: sample_pipeline
    steps:
      - name: step_A
        type: Bash
        configuration:
          inputResources:
            - name: newRepo
          outputResources:
            - name: myVersion
        execution:
          onExecute:
            - write_output myVersion "info=$run_number"
  - name: trigger_pipeline
    steps:
      - name: step_B
        type: Bash
        configuration:
          inputResources:
            - name: myVersion
        execution:
          onExecute:
            - echo $res_myVersion_info
