resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: deepikasl/npmHelloWorld
      gitProvider: deepikaGithub

  - name: npm_build_info_publish
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: npm_publish
      buildNumber: 1
  
  - name: npm_build_info_promoted
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: npm+promote
      buildNumber: 1
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          outputResources:
            - name: helloworld
          integrations:
            - name: art

      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-virtual
          inputResources:
            - name: helloworld
          inputSteps:
            - name: build_npm
          integrations:
            - name: art
