pipelines:
  - name: sample_pipeline_version
    configuration:
      environmentVariables:
        readOnly:
          fooVersion: 0.0.0
        booVersion: 0.0.0
    steps:
      - name: step_1_version
        type: Bash
        execution:
          onExecute:
            - echo "$fooVersion"
            - echo "$booVersion"
      - name: step_2_version
        type: Bash
        configuration:
            inputSteps:
              - name: step_1_version
        execution:
          onExecute:
            - echo "$fooVersion"
            - echo "$booVersion"
